---
workerPool: 10
maxDepth: 2
timeout: 5
initialURL: "https://developer.hashicorp.com/vault"
baseURL: "https://developer.hashicorp.com"
allowedDomains: [https://developer.hashicorp.com/vault]
deniedDomains: [https://releases.hashicorp.com/vault]
