---
# URL used when rewriting local links
baseURL: "https://developer.hashicorp.com"

# Controls what domains the crawler should retrieve
allowedDomains: [https://developer.hashicorp.com/vault]

# Controls what domains the crawler should not retrieve
deniedDomains: [https://releases.hashicorp.com/vault]

# Number of goroutines concurrently retrieving HTML
workerPool: 10

# Controls the maximum depth the BFS will crawl
maxDepth: 2

# HTML client timeout time
timeout: 5
